# -*- coding: utf-8 -*-
"""Copy of Assignment_of_function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQt0YGfyvBT_klZCL1Lv0FqlHiWkF2ev

Movie.ticket.price
"""



# write a function that calculate the movie ticket price based on age (adult, child, senior)#
    # and the day of week weekday weekend #

def ticket():
    price_child=300
    price_adult=420
    price_senior=470
    age=int(input("enter the age:"))

    if age  <18:
        print(price_child,"the price of movie ticket for child")
    elif age >=18 <= 40:
        print(price_senior,"the price of movie ticket for senoir")
    elif age >= 40:
        print(price_adult)
    price1=400
    price2=500
    day = int(input("enter the number of day"))
    if day == 1:
        print(price1)

    if day == 2:
        print(price1)

    if day == 3:
        print(price1)

    if day == 4:
        print(price1)

    if day == 5:
        print(price1)

    if day == 6:
        print(price2)

    if day == 7:
        print(price2)

    groups_pakages=int(input("enter the number of people in groups: "))
    if groups_pakages >=10:
        print(price2 * 0.9,"congratulation for discount you get, enjoy your movie")
    elif groups_pakages <10:
        print("sorry discount is not offer")

ticket()
ticket()
ticket()
ticket()
ticket()
ticket()

